SharedParams:
  - &vocab_path C:\Users\User\Documents\PhD-study\OCR-TextRecognition-Data\Compiled\Sample\Vocab.txt
  - &data_root C:\Users\User\Documents\PhD-study\OCR-TextRecognition-Data\Compiled 
  - &log_dir C:\Users\User\Documents\PhD-study\Logs\attentions-baseline
  - &image_height 64

vocab: *vocab_path
data_registry:
  rootdir: *data_root

model_params:
  model: MultiHeadOcrModel
  input_height: *image_height

  feature_extractor_name: simple
  feature_extractor_params:
    output_channels: 256
  heads_params:
    attn_head:
      type: rnn_attn
      specific_params:
        encoder_lstm_args:
          hidden_size: 128
          bidirectional: True
        decoder_hidden_size: 128
        embedding_size: 128

runner_params:
  attention_heads: True
  max_prediction_length: 10

args:
  logdir: *log_dir
  expdir: src
  seed: 42 
  deterministic: True
  benchmark: True
  verbose: True

stages: 
  data_params:
    dataset_names:
      train: CAR_TRAIN
      valid: CAR_TEST
    image_resize_params:
      # All images are firstly resized to have fixed height keeping aspect ratio
      height: *image_height 
      # Allowed images width range. Smaller images are padded to max_width on the right side
      min_width: 256
      max_width: 256
    num_workers: 0

  criterion_params:
    _key_value: True
    ctc:
      criterion: CTCLoss
      blank: 0
    cross_entropy:
      criterion: CrossEntropyLoss
      ignore_index: -100

  optimizer_params:
    optimizer: Adam
    lr: 0.001
    weight_decay: 0.0001

  scheduler_params:
    scheduler: StepLR
    step_size: 3
    gamma: 0.5

  train_stage: # Training stage
    data_params:
      batch_size: 64
    
    state_params: 
      num_epochs: 9
      main_metric: ctc.fragment_acc
      minimize_metric: False
      valid_loader: valid

    callbacks_params: 
      # Training
      encode_labels_seq:
        callback: EncodeLabelsCallback
        encoder_name: seq
      ce_loss:
        callback: CriterionCallback
        prefix: ce_loss
        criterion_key: cross_entropy
        input_key: seq.labels
        output_key: attn_head.logits
      optimizer:
        metric_key: ce_loss
        callback: OptimizerCallback
      scheduler:
        callback: SchedulerCallback
        mode: epoch
      # Evaluation
      decode_labels_attn:
        callback: DecodeLabelsCallback
        encoder_name: seq
        input_key: attn_head.logits
        output_key: attn_head.string
      metrics_attn:
        callback: OcrMetricsCallback
        prefix: attn
        output_key: attn_head.string
