SharedParams:
  - &vocab_path C:\Users\User\Documents\PhD-study\OCR-TextRecognition-Data\Compiled\AlphanumericWithPunctNoCase.txt
  - &data_root C:\Users\User\Documents\PhD-study\OCR-TextRecognition-Data\Compiled 
  - &log_dir C:\Users\User\Documents\PhD-study\Logs\street-view\mobile-32-100-2x-blstm-256-ctc
  - &image_height 32
  - &image_min_width 32
  - &image_max_width 100

args:
  logdir: *log_dir
  expdir: src
  seed: 42 
  deterministic: True
  benchmark: True
  verbose: True

vocab: *vocab_path
data_registry:
  rootdir: *data_root
  case_sensitive: False
  path_data:
    MJ_train: Synthetic/MJ/MJ_train
    MJ_valid: Synthetic/MJ/MJ_valid
    MJ_test: Synthetic/MJ/MJ_test
    ST_AN: Synthetic/ST_AN
    ST_SPE: Synthetic/ST_spe
    SYNTHADD: Synthetic/SynthAdd
    COCO_TRAIN: Real/Train/COCO_TRAIN
    COCO_VAL: Real/Train/COCO_VAL
    IC03_TRAIN: Real/Train/IC03
    IC13_TRAIN: Real/Train/IC13
    IC15_TRAIN: Real/Train/IC15
    IIIT5K_TRAIN: Real/Train/IIIT5k
    RRC_ART: Real/Train/RRC_ArT
    SVT_TRAIN: Real/Train/SVT
    IC03_TEST: Real/Test/IC03
    IC13_TEST: Real/Test/IC13
    IC15_TEST: Real/Test/IC15
    IIIT5K_TEST: Real/Test/IIIT5K
    SVT_TEST: Real/Test/SVT
    SVTP: Real/Test/SVTP
    CUTE80: Real/Test/CUTE80
  operations:
    - type: merge
      target: SYNTHETIC
      components:
        - MJ_train
        - MJ_valid
        - MJ_test
        - ST_AN
        - ST_SPE
        - SYNTHADD
    - type: merge
      target: REAL_TRAIN
      components:
        - IC13_TRAIN
        - IC15_TRAIN
        - IIIT5K_TRAIN
        - SVT_TRAIN

runner_params:
  device: gpu

model_params:
  model: MultiHeadOcrModel
  input_height: *image_height
  input_width: *image_max_width
  stn_params:
    use: True
    num_fiducial: 20
  feature_extractor_params:
    type: resnet14
  heads_params:
    attn_head:
      type: rnn_attn
      encoder_params:
        mode: none
        args: {}
      decoder_params:
        hidden_size: 256
        embedding_size: 128
        max_num_steps: 25

stages: 
  data_params:
    image_resize_params:
      # All images are firstly resized to have fixed height keeping aspect ratio
      height: *image_height
      # Allowed images width range. Smaller images are padded to max_width on the right side
      min_width: *image_min_width
      max_width: *image_max_width
    num_workers: 0

  optimizer_params:
    optimizer: Adam
    lr: 0.001
    weight_decay: 0

  scheduler_params:
    scheduler: MultiStepLR
    milestones: [100, 150]
    gamma: 0.34

  train_stage: # Network training stage
    data_params:
      batch_size: 100
      num_workers: 1
      dataset_names:
        train: SYNTHETIC
        valid: REAL_TRAIN
      samplers_params:
        train:
          sampler: MiniEpochSampler
          data_len: 17139318
          mini_epoch_len: 400000
          drop_last: True
          shuffle: per_epoch
    
    state_params:
      num_epochs: 200
      main_metric: attn_head.alphanum.fragment_acc
      minimize_metric: False
      valid_loader: valid

    callbacks_params:
      ce_loss:
        callback: CrossEntropyCriterionCallback
        head_key: attn_head
      #ctc_loss:
      #  callback: CtcCriterionCallback
      #  head_key: ctc_head
      total_loss:
        callback: MetricAggregationCallback
        prefix: total_loss
        metrics:
          - attn_head.loss
        #  - ctc_head.loss
        mode: sum
      optimizer:
        callback: OptimizerCallback
        metric_key: total_loss
      scheduler:
        callback: SchedulerCallback
        mode: epoch

  infer_stage: # Inference stage: final testing on main SVT benchmarks
    data_params:
      batch_size: 1
      dataset_names:
        IIIT_infer: IIIT5K_TEST
        SVT_infer: SVT_TEST
        IC03_infer: IC03_TEST
        IC13_infer: IC13_TEST
        IC15_infer: IC15_TEST
        SVTP_infer: SVTP
        CUTE80_infer: CUTE80
    
    state_params:
      num_epochs: 1

    callbacks_params:
      load_best_checkpoint:
        callback: CheckpointCallback
        #load_on_stage_start: best. # Should be added in Catalyst 20.6 and later
      metric_manager:
        callback: MetricManagerCallback
      timer:
        callback: TimerCallback
      console:
        callback: ConsoleLogger
      tensorboard:
        callback: TensorboardLogger
