SharedParams:
  - &vocab_path C:\Users\User\Documents\PhD-study\OCR-TextRecognition-Data\Compiled\AlphanumericWithPunctNoCase.txt
  - &data_root C:\Users\User\Documents\PhD-study\OCR-TextRecognition-Data\Compiled 
  - &log_dir C:\Users\User\Documents\PhD-study\Logs\street-view\resnet14-32-100-blstm-256-ctc-with-attn
  - &image_height 32
  - &image_min_width 32
  - &image_max_width 100

args:
  logdir: *log_dir
  expdir: src
  seed: 42 
  deterministic: True
  benchmark: True
  verbose: True

vocab: *vocab_path
data_registry:
  rootdir: *data_root
  case_sensitive: False
  path_data:
    MJ_train: Synthetic/MJ/MJ_train
    MJ_valid: Synthetic/MJ/MJ_valid
    MJ_test: Synthetic/MJ/MJ_test
    ST_AN: Synthetic/ST_AN
    ST_SPE: Synthetic/ST_spe
    SYNTHADD: Synthetic/SynthAdd
    COCO_TRAIN: Real/Train/COCO_TRAIN
    COCO_VAL: Real/Train/COCO_VAL
    IC03_TRAIN: Real/Train/IC03
    IC13_TRAIN: Real/Train/IC13
    IC15_TRAIN: Real/Train/IC15
    IIIT5K_TRAIN: Real/Train/IIIT5k
    RRC_ART: Real/Train/RRC_ArT
    SVT_TRAIN: Real/Train/SVT
    IC03_TEST: Real/Test/IC03
    IC13_TEST: Real/Test/IC13
    IC15_TEST: Real/Test/IC15
    IC15_1811_TEST: Real/Test/IC15_1811
    IIIT5K_TEST: Real/Test/IIIT5K
    SVT_TEST: Real/Test/SVT
    SVTP: Real/Test/SVTP
    CUTE80: Real/Test/CUTE80
  operations:
    - type: merge
      target: SYNTHETIC
      components:
        - MJ_train
        - MJ_valid
        - MJ_test
        - ST_AN
        - ST_SPE
        - SYNTHADD
    - type: merge
      target: REAL_TRAIN
      components:
        - IC13_TRAIN
        - IC15_TRAIN
        - IIIT5K_TRAIN
        - SVT_TRAIN

model_params:
  model: MultiHeadOcrModel
  input_height: *image_height
  input_width: *image_max_width
  stn_params:
    use: True
    num_fiducial: 20
  feature_extractor_params:
    type: resnet14
    initial_pool: 2
  heads_params:
    attn_head:
      type: rnn_attn
      encoder_params:
        mode: pass
        args:
          hidden_size: 128
          num_layers: 1
          bidirectional: True
      decoder_params:
        hidden_size: 256
        embedding_size: 128
    ctc_head:
      type: ctc
      grad_to_features: True
      lstm_args:
        hidden_size: 256
        num_layers: 1
        bidirectional: True

stages: 
  data_params:
    image_resize_params:
      # All images are firstly resized to have fixed height keeping aspect ratio
      height: *image_height
      # Allowed images width range. Smaller images are padded to max_width on the right side
      min_width: *image_min_width
      max_width: *image_max_width
    num_workers: 0

  infer_stage: # Inference stage: final testing on main SVT benchmarks
    data_params:
      batch_size: 1
      dataset_names:
        IIIT_infer: IIIT5K_TEST
        SVT_infer: SVT_TEST
        IC03_infer: IC03_TEST
        IC13_infer: IC13_TEST
        IC15_infer: IC15_TEST
        IC15_1811_infer: IC15_1811_TEST
        SVTP_infer: SVTP
        CUTE80_infer: CUTE80
    
    state_params:
      num_epochs: 1

    callbacks_params:
      load_best_checkpoint:
        callback: CheckpointCallback
      metric_manager:
        callback: MetricManagerCallback
      timer:
        callback: TimerCallback
      console:
        callback: ConsoleLogger
      tensorboard:
        callback: TensorboardLogger
