SharedParams:
  - &vocab_path C:\Users\User\Documents\PhD-study\OCR-TextRecognition-Data\Compiled\Sample\Vocab.txt
  - &data_root C:\Users\User\Documents\PhD-study\OCR-TextRecognition-Data\Compiled 
  - &log_dir C:\Users\User\Documents\PhD-study\Logs
  - &image_height 64

vocab: *vocab_path
data_registry:
  rootdir: *data_root

model_params:
  model: MultiHeadOcrModel
  input_height: *image_height

  feature_extractor_name: simple
  feature_extractor_params:
    output_channels: 256
  heads_params:
    ctc_head:
      type: lstm_ctc
      specific_params:
        lstm_args:
          hidden_size: 100
          bidirectional: True

args:
  logdir: *log_dir
  expdir: src
  seed: 42 
  deterministic: True  # KEYWORD, whether to use deterministic CuDNN (Default is True)
  benchmark: True  # KEYWORD, whether to use CuDNN benchmark
  verbose: False  # KEYWORD, whether to display learning information on the console (Default is False)

stages:  # REQUIRED KEYWORD, dictionary of all stages of Catalyst, for training and/or infer. Contain keywords with parameters that apply to all the stages, as well as the names of the stages
  data_params:  # KEYWORD, parameters passed to `ConfigExperiment.get_datasets(...)` (for all the stages)
    dataset_names:
      train: CAR_TRAIN
      valid: CAR_TEST
    image_resize_params:
      # All images are firstly resized to have fixed height keeping aspect ratio
      height: *image_height 
      # Allowed images width range. Smaller images are padded to max_width on the right side
      min_width: 256
      max_width: 256
    num_workers: 0  # KEYWORD, Number of parallel processes for DataLoader
    drop_last: False  # KEYWORD, parameter for DataLoader (Default is False)

  criterion_params:  # REQUIRED KEYWORD, parameters for the loss function
    _key_value: True
    ctc:
      criterion: CTCLoss
      blank: 0

  optimizer_params:
    optimizer: Adam
    lr: 0.001
    weight_decay: 0.0001

  scheduler_params:  # REQUIRED KEYWORD, params for lr-scheduler
    scheduler: StepLR  # REQUIRED KEYWORD, name of the lr-scheduler
    step_size: 10
    gamma: 0.3

  train: # Training stage
    data_params:
      batch_size: 32
    
    state_params:  # You can override any parameters for a particular stage, for example
      num_epochs: 3
      main_metric: ctc_loss
      minimize_metric: False  # REQUIRED KEYWORD, flag, should we minimize `main_metric`
      valid_loader: valid  # KEYWORD, name of the loader by which the checkpoints will be taken

    callbacks_params: 
      encode_labels:
        callback: EncodeLabelsCallback
        encoder_name: ctc
      #debug:
      #  callback: DebugCallback
      ctc_loss:
        callback: CriterionCallback
        prefix: ctc_loss
        criterion_key: ctc
        input_key:
          ctc.labels: targets
          ctc.label_lengths: target_lengths
        output_key:
          ctc_head.logprobs: log_probs
          ctc_head.logprobs_len: input_lengths
      optimizer:
        metric_key: ctc_loss
        callback: OptimizerCallback
      scheduler:
        callback: SchedulerCallback
      saver:
        callback: CheckpointCallback
