SharedParams:
  - &vocab_path C:\Users\User\Documents\PhD-study\OCR-TextRecognition-Data\Compiled\Sample\Vocab.txt
  - &data_root C:\Users\User\Documents\PhD-study\OCR-TextRecognition-Data\Compiled 
  - &log_dir C:\Users\User\Documents\PhD-study\Logs\sample-baseline
  - &image_height 64

vocab: *vocab_path
data_registry:
  rootdir: *data_root

model_params:
  model: MultiHeadOcrModel
  input_height: *image_height

  feature_extractor_name: simple
  feature_extractor_params:
    output_channels: 256
  heads_params:
    attn_head:
      type: rnn_attn
      specific_params:
        encoder_lstm_args:
          hidden_size: 128
          bidirectional: True
        decoder_hidden_size: 128
        embedding_size: 128
#    ctc_head:
#      type: lstm_ctc
#      specific_params:
#        lstm_args:
#          hidden_size: 128
#          bidirectional: True

runner_params:
  attention_heads: True
  max_prediction_length: 10

args:
  logdir: *log_dir
  expdir: src
  seed: 42 
  deterministic: True
  benchmark: True
  verbose: True

stages: 
  data_params:
    dataset_names:
      train: CAR_TRAIN
      valid: CAR_TEST
    image_resize_params:
      # All images are firstly resized to have fixed height keeping aspect ratio
      height: *image_height 
      # Allowed images width range. Smaller images are padded to max_width on the right side
      min_width: 256
      max_width: 256
    num_workers: 0

  criterion_params:
    _key_value: True
    ctc:
      criterion: CTCLoss
      blank: 0
    cross_entropy:
      criterion: CrossEntropyLoss
      ignore_index: -100

  optimizer_params:
    optimizer: Adam
    lr: 0.001
    weight_decay: 0.0001

  scheduler_params:
    scheduler: StepLR
    step_size: 3
    gamma: 0.5

  train_stage: # Training stage
    data_params:
      batch_size: 64
    
    state_params: 
      num_epochs: 9
      main_metric: attn.fragment_acc #ctc.fragment_acc
      minimize_metric: False
      valid_loader: valid

    callbacks_params: 
      # Training
      encode_labels:
        callback: EncodeLabelsCallback
        encoder_name: ctc
      encode_labels:
        callback: EncodeLabelsCallback
        encoder_name: seq
      ce_loss:
        callback: CriterionCallback
        prefix: ce_loss
        criterion_key: cross_entropy
        input_key: seq.labels
        output_key: attn_head.logits
      #ctc_loss:
      #  callback: CriterionCallback
      #  prefix: ctc_loss
      #  criterion_key: ctc
      #  input_key:
      #    ctc.labels: targets
      #    ctc.label_lengths: target_lengths
      #  output_key:
      #    ctc_head.logprobs: log_probs
      #    ctc_head.logprobs_len: input_lengths
      optimizer:
        #metric_key: ctc_loss
        metric_key: ce_loss
        callback: OptimizerCallback
      scheduler:
        callback: SchedulerCallback
        mode: epoch
      # Evaluation
      #decode_labels:
      #  callback: DecodeLabelsCallback
      #  encoder_name: ctc
      #  input_key: ctc_head.logprobs
      #  output_key: ctc_head.string
      decode_labels:
        callback: DecodeLabelsCallback
        encoder_name: seq
        input_key: attn_head.logits
        output_key: attn_head.string
      metrics:
        callback: OcrMetricsCallback
        #prefix: ctc
        prefix: attn
        #output_key: ctc_head.string
        output_key: attn_head.string
