SharedParams:
  - &vocab_path C:\Users\User\Documents\PhD-study\OCR-TextRecognition-Data\Compiled\Sample\Vocab.txt
  - &data_root C:\Users\User\Documents\PhD-study\OCR-TextRecognition-Data\Compiled 
  - &log_dir C:\Users\User\Documents\PhD-study\Logs\car-plates\gtc
  - &image_height 64

args:
  logdir: *log_dir
  expdir: src
  seed: 42 
  deterministic: True
  benchmark: True
  verbose: True

vocab: *vocab_path
data_registry:
  rootdir: *data_root
  path_data:
    CAR_TRAIN_VAL: Sample/Train
    CAR_TEST: Sample/Test
  operations:
    - type: split
      main: CAR_TRAIN_VAL
      first: CAR_TRAIN
      second: CAR_VAL
      first_size: 0.8
      shuffle: True

model_params:
  model: MultiHeadOcrModel
  input_height: *image_height

  feature_extractor_name: simple
  feature_extractor_params:
    output_channels: 256
  heads_params:
    attn_head:
      type: rnn_attn
      specific_params:
        max_num_steps: 10
        encoder_lstm_args:
          hidden_size: 128
          bidirectional: True
        decoder_hidden_size: 128
        embedding_size: 128
    ctc_head:
      type: ctc
      specific_params:
        grad_to_features: False
        lstm_args:
          hidden_size: 128
          bidirectional: True

stages: 
  data_params:
    image_resize_params:
      # All images are firstly resized to have fixed height keeping aspect ratio
      height: *image_height 
      # Allowed images width range. Smaller images are padded to max_width on the right side
      min_width: 256
      max_width: 256
    num_workers: 0

  optimizer_params:
    optimizer: Adam
    lr: 0.001
    weight_decay: 0.0001

  scheduler_params:
    scheduler: ReduceLROnPlateau
    patience: 5
    factor: 0.5

  train_stage: # Network training stage
    data_params:
      batch_size: 64
      dataset_names:
        train: CAR_TRAIN
        valid: CAR_VAL
    
    state_params:
      num_epochs: 40
      main_metric: total_loss
      valid_loader: valid

    callbacks_params:
      ce_loss:
        callback: CrossEntropyCriterionCallback
        head_key: attn_head
      ctc_loss:
        callback: CtcCriterionCallback
        head_key: ctc_head
      total_loss:
        callback: MetricAggregationCallback
        prefix: total_loss
        metrics:
          - attn_head.loss
          - ctc_head.loss
        mode: sum
      optimizer:
        callback: OptimizerCallback
        metric_key: total_loss
      scheduler:
        callback: SchedulerCallback
        mode: epoch
        reduced_metric: total_loss

  infer_stage: # Inference stage: final testing on several datasets
    data_params:
      batch_size: 1
      dataset_names:
        car_test: CAR_TEST
    
    state_params: 
      num_epochs: 1

    callbacks_params:
      load_best_checkpoint:
        callback: CheckpointCallback
        #load_on_stage_start: best. # Should be added in Catalyst 20.6 and later
      metric_manager:
        callback: MetricManagerCallback
      console:
        callback: ConsoleLogger
      tensorboard:
        callback: TensorboardLogger
